
# Key = value pair of the data that you dpn't want to hardcode.
#Project 1 - app.vwo.com
url=https://app.vwo.com
username=ceyapob638@deposin.com
password=Vinay@1234
expected_username=Deposin

invalid_username=admin@admin.com
invalid_password=Test@2024


error_message=Your email, password, IP address or location did not match
invalid_error_message=Vinay email, password, IP address or location did not match
browser=Chrome


# Project 2 - Orange HR
ohr_username=admin
ohr_password=Hacker@4321
ohr_expected_username=PIM
ohr_url = https://awesomeqa.com/hr/web/index.php/auth/login


# Project 3 - Katalon App
katalon_url=https://katalon-demo-cura.herokuapp.com/
